In [2]:
import pandas as pd
import numpy as np 
from sklearn.preprocessing import LabelEncoder 
from sklearn.preprocessing import OrdinalEncoder 
import warnings
warnings.filterwarnings("ignore")

In [3]:


X_train = [['40-49', 'premeno', '10-14', '0-2', 'no', '1', 'right', 'right_low', 'no'], ['50-59',
'ge40', '10-14', '0-2', 'no', '1', 'right', 'left_up', 'no'], ['40-49', 'ge40', '20-24', '0-2',
'no', '3', 'left', 'left_low', 'no'], ['60-69', 'ge40', '30-34', '3-5', 'yes', '2', 'left',
'central', 'yes'], ['50-59', 'ge40', '40-44', '0-2', 'no', '3', 'left', 'right_up', 'no'],
['50-59', 'ge40', '35-39', '0-2', 'no', '3', 'left', 'left_low', 'no'], ['60-69', 'ge40',
'40-44', '3-5', 'yes', '3', 'right', 'left_low', 'no'], ['50-59', 'ge40', '30-34', '6-8', 'yes',
'3', 'left', 'right_low', 'no'], ['60-69', 'ge40', '10-14', '0-2', 'no', '1', 'left', 'left_up',
'no'], ['40-49', 'premeno', '30-34', '0-2', 'no', '1', 'left', 'left_low', 'yes'], ['50-59',
'premeno', '30-34', '0-2', 'no', '3', 'left', 'left_low', 'no'], ['40-49', 'premeno', '15-19',
'0-2', 'no', '2', 'left', 'left_low', 'no'], ['30-39', 'premeno', '20-24', '3-5', 'yes', '2',
'left', 'left_low', 'no'], ['40-49', 'premeno', '20-24', '0-2', 'no', '1', 'right', 'right_up',
'no'], ['40-49', 'premeno', '20-24', '0-2', 'no', '2', 'left', 'left_low', 'no'], ['50-59',
'ge40', '20-24', '0-2', 'no', '3', 'left', 'left_up', 'no'], ['40-49', 'premeno', '25-29',
'0-2', 'no', '2', 'left', 'left_low', 'yes'], ['40-49', 'premeno', '35-39', '0-2', 'no', '1',
'left', 'left_low', 'no'], ['40-49', 'premeno', '50-54', '0-2', 'no', '2', 'right', 'left_low',
'yes'], ['30-39', 'premeno', '15-19', '0-2', 'no', '1', 'left', 'left_low', 'no'], ['60-69',
'ge40', '10-14', '0-2', 'no', '1', 'left', 'left_low', 'no'], ['40-49', 'premeno', '30-34',
'0-2', 'no', '3', 'right', 'right_up', 'no'], ['30-39', 'lt40', '15-19', '0-2', 'no', '3',
'right', 'left_up', 'no'], ['50-59', 'ge40', '40-44', '6-8', 'yes', '3', 'left', 'left_low',
'yes'], ['60-69', 'ge40', '30-34', '6-8', 'yes', '2', 'right', 'right_up', 'no'], ['50-59',
'premeno', '35-39', '15-17', 'yes', '3', 'right', 'right_up', 'no'], ['40-49', 'premeno', '50-54',
'0-2', 'no', '2', 'left', 'left_low', 'no'], ['40-49', 'premeno', '35-39', '0-2', 'no', '1',
'right', 'left_up', 'no'], ['50-59', 'ge40', '20-24', '0-2', 'no', '1', 'right', 'left_low',
'no'], ['40-49', 'premeno', '45-49', '0-2', 'no', '2', 'left', 'left_low', 'yes'], ['40-49',
'premeno', '0-4', '0-2', 'no', '2', 'right', 'right_low', 'no'], ['40-49', 'premeno', '25-29',
'0-2', 'no', '1', 'left', 'right_low', 'no'], ['40-49', 'ge40', '20-24', '3-5', 'no', '3',
'right', 'left_low', 'yes'], ['60-69', 'ge40', '25-29', '3-5', 'nan', '1', 'right', 'left_low',
'yes'], ['30-39', 'premeno', '25-29', '0-2', 'no', '2', 'left', 'left_low', 'no'], ['50-59',
'ge40', '25-29', '15-17', 'yes', '3', 'right', 'left_up', 'no'], ['40-49', 'premeno', '10-14',
'0-2', 'no', '2', 'right', 'left_low', 'no'], ['50-59', 'ge40', '25-29', '0-2', 'no', '1',
'left', 'right_low', 'no'], ['30-39', 'premeno', '5-9', '0-2', 'no', '2', 'left', 'right_low',
'no'], ['50-59', 'premeno', '50-54', '0-2', 'yes', '2', 'right', 'left_up', 'yes'], ['30-39',
'premeno', '25-29', '0-2', 'no', '1', 'left', 'central', 'no'], ['40-49', 'premeno', '20-24',
'0-2', 'no', '2', 'right', 'right_up', 'no'], ['40-49', 'premeno', '10-14', '0-2', 'no', '2',
'left', 'left_low', 'yes'], ['50-59', 'ge40', '20-24', '0-2', 'no', '3', 'right', 'left_up',
'no'], ['50-59', 'premeno', '10-14', '0-2', 'no', '2', 'right', 'left_up', 'no'], ['50-59',
'premeno', '25-29', '3-5', 'yes', '2', 'left', 'left_low', 'yes'], ['30-39', 'premeno', '15-19',
'0-2', 'no', '1', 'left', 'left_low', 'no'], ['40-49', 'premeno', '30-34', '0-2', 'no', '3',
'right', 'right_up', 'no'], ['40-49', 'premeno', '30-34', '15-17', 'yes', '3', 'left', 'left_low',
'no'], ['40-49', 'premeno', '15-19', '15-17', 'yes', '3', 'left', 'left_low', 'no'], ['40-49',
'premeno', '15-19', '0-2', 'yes', '3', 'right', 'left_up', 'no'], ['60-69', 'ge40', '30-34',
'0-2', 'no', '3', 'left', 'left_low', 'no'], ['40-49', 'premeno', '20-24', '0-2', 'no', '1',
'right', 'left_low', 'no'], ['30-39', 'premeno', '25-29', '0-2', 'no', '2', 'right', 'left_low',
'no'], ['60-69', 'ge40', '15-19', '0-2', 'no', '2', 'left', 'left_low', 'no'], ['30-39',
'premeno', '30-34', '9-11', 'no', '2', 'right', 'left_up', 'yes'], ['60-69', 'ge40', '20-24',
'3-5', 'no', '2', 'left', 'left_low', 'yes'], ['60-69', 'ge40', '30-34', '3-5', 'yes', '3',
'left', 'left_low', 'no'], ['50-59', 'premeno', '10-14', '3-5', 'no', '1', 'right', 'left_up',
'no'], ['40-49', 'ge40', '30-34', '3-5', 'no', '3', 'left', 'left_low', 'no'], ['50-59',
'premeno', '35-39', '0-2', 'no', '2', 'right', 'left_up', 'no'], ['40-49', 'premeno', '25-29',
'0-2', 'no', '3', 'left', 'right_up', 'no'], ['60-69', 'ge40', '25-29', '0-2', 'no', '2',
'left', 'left_low', 'no'], ['50-59', 'ge40', '35-39', '0-2', 'no', '2', 'left', 'left_up',
'no'], ['40-49', 'premeno', '35-39', '0-2', 'yes', '3', 'right', 'left_up', 'yes'], ['60-69',
'lt40', '30-34', '0-2', 'no', '1', 'left', 'left_low', 'no'], ['40-49', 'premeno', '20-24',
'6-8', 'no', '2', 'right', 'left_low', 'yes'], ['30-39', 'premeno', '30-34', '3-5', 'no', '3',
'right', 'left_up', 'yes'], ['40-49', 'premeno', '25-29', '0-2', 'no', '3', 'left', 'left_up',
'no'], ['30-39', 'premeno', '35-39', '0-2', 'no', '3', 'left', 'left_low', 'no'], ['60-69',
'ge40', '40-44', '3-5', 'no', '2', 'right', 'left_up', 'yes'], ['50-59', 'premeno', '15-19',
'0-2', 'no', '2', 'left', 'left_low', 'no'], ['30-39', 'premeno', '10-14', '0-2', 'no', '1',
'right', 'left_low', 'no'], ['70-79', 'ge40', '40-44', '0-2', 'no', '1', 'right', 'right_up',
'no'], ['50-59', 'ge40', '10-14', '0-2', 'no', '1', 'left', 'left_up', 'no'], ['40-49',
'premeno', '5-9', '0-2', 'no', '1', 'left', 'left_low', 'yes'], ['40-49', 'premeno', '30-34',
'6-8', 'yes', '3', 'right', 'left_up', 'no'], ['50-59', 'premeno', '30-34', '0-2', 'no', '3',
'right', 'left_up', 'yes'], ['50-59', 'premeno', '30-34', '0-2', 'no', '1', 'left', 'central',
'no'], ['50-59', 'premeno', '20-24', '0-2', 'no', '1', 'left', 'left_low', 'no'], ['40-49',
'premeno', '30-34', '0-2', 'no', '2', 'right', 'right_up', 'yes'], ['60-69', 'ge40', '10-14',
'0-2', 'no', '2', 'left', 'left_low', 'no'], ['50-59', 'ge40', '20-24', '0-2', 'yes', '2',
'right', 'left_up', 'no'], ['30-39', 'premeno', '0-4', '0-2', 'no', '2', 'right', 'central',
'no'], ['60-69', 'ge40', '25-29', '0-2', 'no', '3', 'right', 'left_up', 'no'], ['60-69', 'ge40',
'5-9', '0-2', 'no', '1', 'left', 'central', 'no'], ['70-79', 'ge40', '20-24', '0-2', 'no',
'3', 'left', 'left_up', 'no'], ['50-59', 'premeno', '15-19', '0-2', 'no', '2', 'right',
'right_low', 'no'], ['40-49', 'premeno', '35-39', '9-11', 'yes', '2', 'right', 'left_up', 'yes'],
['50-59', 'ge40', '25-29', '0-2', 'no', '2', 'left', 'left_low', 'no'], ['50-59', 'premeno',
'10-14', '0-2', 'no', '3', 'left', 'left_low', 'no'], ['60-69', 'ge40', '15-19', '0-2', 'no',
'3', 'right', 'left_up', 'yes'], ['40-49', 'premeno', '25-29', '0-2', 'no', '2', 'left',
'left_up', 'yes'], ['40-49', 'premeno', '25-29', '0-2', 'nan', '2', 'left', 'right_low', 'yes'],
['50-59', 'ge40', '40-44', '0-2', 'no', '2', 'left', 'left_low', 'no'], ['40-49', 'premeno',
'30-34', '6-8', 'no', '2', 'left', 'left_up', 'no'], ['40-49', 'premeno', '20-24', '3-5', 'no',
'2', 'right', 'left_up', 'no'], ['40-49', 'premeno', '40-44', '3-5', 'yes', '3', 'right',
'left_up', 'yes'], ['60-69', 'ge40', '30-34', '0-2', 'no', '3', 'right', 'left_up', 'yes'],
['30-39', 'premeno', '40-44', '0-2', 'no', '2', 'right', 'right_up', 'no'], ['40-49', 'premeno',
'30-34', '0-2', 'no', '2', 'left', 'right_low', 'no'], ['50-59', 'premeno', '10-14', '0-2',
'no', '1', 'left', 'left_low', 'no'], ['50-59', 'ge40', '30-34', '0-2', 'no', '3', 'left',
'nan', 'no'], ['40-49', 'premeno', '30-34', '0-2', 'no', '1', 'right', 'left_up', 'no'], ['40-49',
'premeno', '20-24', '0-2', 'no', '2', 'left', 'left_up', 'no'], ['50-59', 'ge40', '40-44',
'6-8', 'yes', '3', 'left', 'left_low', 'yes'], ['50-59', 'ge40', '20-24', '0-2', 'no', '2',
'right', 'left_up', 'no'], ['60-69', 'ge40', '20-24', '24-26', 'yes', '3', 'left', 'left_low',
'yes'], ['40-49', 'premeno', '30-34', '0-2', 'no', '3', 'left', 'left_up', 'no'], ['40-49',
'premeno', '40-44', '0-2', 'no', '2', 'right', 'left_low', 'no'], ['50-59', 'ge40', '40-44',
'3-5', 'yes', '2', 'left', 'left_low', 'no'], ['40-49', 'premeno', '30-34', '3-5', 'yes', '2',
'right', 'left_low', 'no'], ['30-39', 'premeno', '20-24', '0-2', 'no', '2', 'left', 'right_low',
'no'], ['40-49', 'premeno', '25-29', '0-2', 'no', '2', 'right', 'left_low', 'no'], ['30-39',
'premeno', '10-14', '0-2', 'no', '2', 'left', 'right_low', 'no'], ['60-69', 'ge40', '30-34',
'0-2', 'yes', '2', 'right', 'right_up', 'yes'], ['40-49', 'premeno', '40-44', '0-2', 'no', '1',
'left', 'left_low', 'no'], ['50-59', 'ge40', '25-29', '0-2', 'no', '2', 'right', 'left_up',
'no'], ['30-39', 'premeno', '40-44', '0-2', 'no', '1', 'left', 'left_up', 'no'], ['50-59',
'premeno', '25-29', '0-2', 'no', '2', 'left', 'left_low', 'no'], ['50-59', 'premeno', '30-34',
'0-2', 'no', '3', 'left', 'right_up', 'no'], ['50-59', 'ge40', '5-9', '0-2', 'no', '2',
'right', 'right_up', 'no'], ['60-69', 'ge40', '20-24', '0-2', 'no', '2', 'left', 'left_up',
'no'], ['40-49', 'premeno', '10-14', '0-2', 'no', '2', 'right', 'left_up', 'no'], ['60-69',
'ge40', '25-29', '0-2', 'no', '3', 'left', 'right_low', 'yes'], ['50-59', 'lt40', '20-24',
'0-2', 'nan', '1', 'left', 'left_low', 'no'], ['40-49', 'premeno', '10-14', '0-2', 'no', '2',
'left', 'left_low', 'no'], ['50-59', 'ge40', '30-34', '6-8', 'yes', '2', 'left', 'left_low',
'no'], ['50-59', 'ge40', '10-14', '0-2', 'no', '1', 'left', 'left_low', 'no'], ['50-59',
'premeno', '15-19', '0-2', 'no', '2', 'right', 'left_low', 'no'], ['50-59', 'ge40', '0-4',
'0-2', 'no', '2', 'left', 'central', 'no'], ['70-79', 'ge40', '0-4', '0-2', 'no', '1', 'left',
'right_low', 'no'], ['60-69', 'ge40', '15-19', '0-2', 'no', '2', 'left', 'left_low', 'no'],
['50-59', 'ge40', '35-39', '0-2', 'no', '2', 'left', 'left_low', 'no'], ['40-49', 'premeno',
'30-34', '0-2', 'no', '2', 'right', 'right_low', 'no'], ['50-59', 'ge40', '40-44', '0-2', 'no',
'3', 'left', 'left_up', 'no'], ['40-49', 'premeno', '15-19', '0-2', 'no', '2', 'left',
'left_up', 'no'], ['50-59', 'ge40', '30-34', '9-11', 'yes', '3', 'left', 'right_low', 'yes'],
['40-49', 'premeno', '25-29', '0-2', 'no', '2', 'right', 'central', 'no'], ['30-39', 'premeno',
'40-44', '3-5', 'no', '3', 'right', 'right_up', 'yes'], ['50-59', 'ge40', '15-19', '0-2', 'no',
'1', 'right', 'central', 'no'], ['50-59', 'ge40', '30-34', '3-5', 'no', '3', 'left', 'left_low',
'no'], ['50-59', 'ge40', '15-19', '0-2', 'no', '2', 'right', 'right_up', 'no'], ['50-59',
'ge40', '25-29', '3-5', 'yes', '3', 'right', 'left_up', 'no'], ['60-69', 'ge40', '10-14', '0-2',
'no', '2', 'right', 'left_up', 'yes'], ['50-59', 'premeno', '25-29', '0-2', 'no', '2', 'left',
'right_up', 'no'], ['30-39', 'premeno', '25-29', '6-8', 'yes', '3', 'left', 'right_low', 'yes'],
['50-59', 'lt40', '20-24', '0-2', 'nan', '1', 'left', 'left_up', 'no'], ['60-69', 'ge40', '20-24',
'0-2', 'no', '3', 'right', 'left_low', 'no'], ['60-69', 'ge40', '20-24', '0-2', 'no', '2',
'right', 'left_up', 'no'], ['30-39', 'premeno', '25-29', '6-8', 'yes', '2', 'right', 'left_up',
'yes'], ['50-59', 'premeno', '20-24', '3-5', 'yes', '2', 'left', 'left_low', 'no'], ['40-49',
'premeno', '20-24', '3-5', 'no', '2', 'right', 'left_low', 'no'], ['50-59', 'premeno', '25-29',
'0-2', 'no', '2', 'left', 'left_low', 'no'], ['60-69', 'ge40', '50-54', '0-2', 'no', '2',
'left', 'left_low', 'no'], ['50-59', 'ge40', '25-29', '0-2', 'no', '3', 'left', 'right_up',
'no'], ['50-59', 'ge40', '0-4', '0-2', 'no', '1', 'right', 'central', 'no'], ['60-69', 'ge40',
'25-29', '3-5', 'no', '2', 'right', 'right_up', 'no'], ['60-69', 'ge40', '15-19', '0-2', 'no',
'2', 'left', 'left_up', 'yes'], ['50-59', 'ge40', '10-14', '0-2', 'no', '2', 'left', 'left_low',
'no'], ['50-59', 'ge40', '30-34', '6-8', 'yes', '2', 'left', 'right_low', 'yes'], ['60-69',
'lt40', '10-14', '0-2', 'no', '1', 'left', 'right_up', 'no'], ['40-49', 'premeno', '20-24',
'3-5', 'yes', '2', 'left', 'left_low', 'yes'], ['50-59', 'ge40', '30-34', '0-2', 'no', '1',
'right', 'left_low', 'no'], ['40-49', 'premeno', '10-14', '0-2', 'no', '1', 'right', 'left_up',
'no'], ['60-69', 'ge40', '30-34', '0-2', 'no', '2', 'left', 'left_up', 'no'], ['30-39',
'premeno', '20-24', '3-5', 'no', '2', 'right', 'central', 'no'], ['40-49', 'ge40', '40-44',
'15-17', 'yes', '2', 'right', 'left_up', 'yes'], ['50-59', 'ge40', '30-34', '9-11', 'nan', '3',
'left', 'left_low', 'yes'], ['40-49', 'premeno', '20-24', '0-2', 'no', '1', 'left', 'right_low',
'no'], ['30-39', 'premeno', '25-29', '3-5', 'yes', '3', 'left', 'left_low', 'yes'], ['40-49',
'premeno', '30-34', '0-2', 'no', '1', 'left', 'left_low', 'no'], ['30-39', 'premeno', '15-19',
'0-2', 'no', '1', 'right', 'left_low', 'no'], ['60-69', 'ge40', '20-24', '0-2', 'no', '1',
'left', 'left_low', 'no'], ['60-69', 'ge40', '25-29', '0-2', 'no', '3', 'right', 'left_low',
'no'], ['60-69', 'ge40', '30-34', '0-2', 'no', '2', 'left', 'left_low', 'yes'], ['50-59',
'ge40', '20-24', '3-5', 'yes', '2', 'right', 'left_up', 'no'], ['50-59', 'premeno', '25-29',
'0-2', 'no', '1', 'left', 'left_low', 'no'], ['40-49', 'ge40', '20-24', '0-2', 'no', '2',
'right', 'left_up', 'no'], ['30-39', 'premeno', '20-24', '0-2', 'no', '3', 'left', 'central',
'no'], ['40-49', 'ge40', '25-29', '12-14', 'yes', '3', 'left', 'right_low', 'yes'], ['40-49',
'premeno', '35-39', '9-11', 'yes', '2', 'right', 'right_up', 'yes'], ['50-59', 'ge40', '20-24',
'0-2', 'no', '2', 'left', 'left_up', 'no'], ['40-49', 'premeno', '20-24', '0-2', 'no', '2',
'left', 'right_low', 'no'], ['50-59', 'lt40', '15-19', '0-2', 'no', '2', 'left', 'left_low',
'no'], ['40-49', 'premeno', '0-4', '0-2', 'no', '3', 'left', 'central', 'no'], ['50-59', 'ge40',
'10-14', '0-2', 'no', '2', 'right', 'left_low', 'no'], ['50-59', 'premeno', '15-19', '0-2',
'no', '1', 'left', 'left_low', 'no'], ['50-59', 'ge40', '20-24', '3-5', 'yes', '3', 'right',
'right_up', 'no'], ['60-69', 'ge40', '30-34', '0-2', 'no', '1', 'left', 'left_up', 'no'],
['30-39', 'premeno', '15-19', '6-8', 'yes', '3', 'left', 'left_low', 'yes'], ['30-39', 'premeno',
'30-34', '0-2', 'no', '1', 'right', 'left_up', 'no'], ['40-49', 'premeno', '35-39', '0-2',
'yes', '3', 'right', 'left_low', 'yes'], ['50-59', 'ge40', '35-39', '15-17', 'no', '3', 'left',
'left_low', 'no'], ['50-59', 'ge40', '40-44', '0-2', 'no', '3', 'right', 'left_up', 'no'],
['50-59', 'ge40', '30-34', '9-11', 'nan', '3', 'left', 'left_up', 'yes'], ['40-49', 'premeno',
'15-19', '12-14', 'no', '3', 'right', 'right_low', 'yes'], ['20-29', 'premeno', '35-39', '0-2',
'no', '2', 'right', 'right_up', 'no'], ['40-49', 'premeno', '35-39', '0-2', 'no', '2', 'right',
'right_up', 'no'], ['60-69', 'ge40', '30-34', '0-2', 'no', '3', 'right', 'central', 'no'],
['50-59', 'premeno', '25-29', '0-2', 'yes', '2', 'left', 'left_up', 'no'], ['60-69', 'ge40',
'10-14', '0-2', 'no', '1', 'left', 'left_up', 'no'], ['40-49', 'premeno', '20-24', '0-2', 'no',
'3', 'right', 'left_low', 'yes'], ['60-69', 'ge40', '25-29', '0-2', 'no', '3', 'left',
'left_up', 'no'], ['40-49', 'premeno', '25-29', '0-2', 'no', '1', 'right', 'left_low', 'yes'],
['50-59', 'ge40', '15-19', '0-2', 'no', '1', 'right', 'central', 'no'], ['50-59', 'ge40',
'15-19', '0-2', 'no', '2', 'right', 'left_low', 'no'], ['40-49', 'premeno', '10-14', '0-2',
'no', '2', 'left', 'left_up', 'no'], ['40-49', 'premeno', '25-29', '0-2', 'no', '2', 'left',
'left_up', 'no'], ['40-49', 'premeno', '40-44', '0-2', 'no', '1', 'right', 'left_up', 'no'],
['70-79', 'ge40', '10-14', '0-2', 'no', '2', 'left', 'central', 'no'], ['70-79', 'ge40',
'40-44', '0-2', 'no', '1', 'right', 'left_up', 'no'], ['50-59', 'premeno', '50-54', '9-11',
'yes', '2', 'right', 'left_up', 'no'], ['70-79', 'ge40', '15-19', '9-11', 'nan', '1', 'left',
'left_low', 'yes'], ['30-39', 'premeno', '30-34', '0-2', 'no', '2', 'left', 'left_up', 'no'],
['40-49', 'premeno', '30-34', '0-2', 'no', '1', 'left', 'right_up', 'no'], ['40-49', 'premeno',
'25-29', '0-2', 'no', '3', 'right', 'left_up', 'yes'], ['40-49', 'premeno', '25-29', '0-2',
'no', '2', 'right', 'left_low', 'no'], ['40-49', 'premeno', '30-34', '12-14', 'yes', '3',
'left', 'left_up', 'yes'], ['60-69', 'ge40', '25-29', '3-5', 'nan', '1', 'right', 'left_up',
'yes'], ['60-69', 'ge40', '15-19', '0-2', 'no', '2', 'right', 'left_low', 'no'], ['50-59',
'ge40', '15-19', '0-2', 'yes', '2', 'left', 'central', 'yes'], ['40-49', 'premeno', '25-29',
'0-2', 'no', '2', 'right', 'left_low', 'no'], ['40-49', 'premeno', '25-29', '0-2', 'no', '1',
'right', 'right_low', 'no'], ['50-59', 'premeno', '25-29', '0-2', 'no', '3', 'right', 'left_low',
'yes'], ['60-69', 'ge40', '10-14', '0-2', 'no', '1', 'right', 'left_low', 'no'], ['60-69',
'ge40', '40-44','0-2','no','2','right', 'left_low','no'], ['60-69','ge40','45-49','6-8','yes',
'3', 'left', 'central', 'no']] 

y_train = [['no-recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'], ['recurrence-events'],
['no-recurrence-events'], ['no-recurrence-events'], ['recurrence-events'], ['recurrence-events'],
['no-recurrence-events'], ['recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'],
['recurrence-events'], ['no-recurrence-events'], ['recurrence-events'], ['no-recurrence-events'],
['recurrence-events'], ['no-recurrence-events'], ['recurrence-events'], ['no-recurrence-events'],
['no-recurrence-events'], ['recurrence-events'], ['no-recurrence-events'], ['recurrence-events'],
['no-recurrence-events'], ['recurrence-events'], ['no-recurrence-events'], ['recurrence-events'],
['no-recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'],
['recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'],
['no-recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'],
['no-recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'],
['no-recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'],
['recurrence-events'], ['recurrence-events'], ['recurrence-events'], ['no-recurrence-events'],
['no-recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'], ['recurrence-events'],
['recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'], ['recurrence-events'],
['no-recurrence-events'], ['recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'],
['no-recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'], ['recurrence-events'],
['recurrence-events'], ['recurrence-events'], ['no-recurrence-events'], ['recurrence-events'],
['no-recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'],
['recurrence-events'], ['recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'],
['no-recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'],
['no-recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'],
['no-recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'],
['no-recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'],
['no-recurrence-events'], ['no-recurrence-events'], ['recurrence-events'], ['no-recurrence-events'],
['no-recurrence-events'], ['no-recurrence-events'], ['recurrence-events'], ['no-recurrence-events'],
['no-recurrence-events'], ['recurrence-events'], ['no-recurrence-events'], ['recurrence-events'],
['no-recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'],
['no-recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'], ['recurrence-events'],
['recurrence-events'], ['no-recurrence-events'], ['recurrence-events'], ['no-recurrence-events'],
['recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'],
['recurrence-events'], ['recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'],
['no-recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'],
['no-recurrence-events'], ['recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'],
['recurrence-events'], ['recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'],
['no-recurrence-events'], ['recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'],
['no-recurrence-events'], ['recurrence-events'], ['recurrence-events'], ['recurrence-events'],
['recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'],
['no-recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'],
['no-recurrence-events'], ['recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'],
['recurrence-events'], ['no-recurrence-events'], ['recurrence-events'], ['no-recurrence-events'],
['no-recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'],
['no-recurrence-events'], ['no-recurrence-events'], ['recurrence-events'], ['no-recurrence-events'],
['recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'],
['no-recurrence-events'], ['no-recurrence-events'], ['recurrence-events'], ['no-recurrence-events'],
['recurrence-events'], ['no-recurrence-events'], ['recurrence-events'], ['no-recurrence-events'],
['no-recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'],
['recurrence-events'], ['no-recurrence-events'], ['recurrence-events'], ['recurrence-events'],
['no-recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'],
['no-recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'], ['recurrence-events'],
['no-recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'], ['recurrence-events'],
['no-recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'],
['no-recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'], ['no-recurrence-events'],
['recurrence-events'], ['recurrence-events'], ['recurrence-events'], ['no-recurrence-events'],
['no-recurrence-events'], ['recurrence-events'], ['recurrence-events'], ['no-recurrence-events'],
['no-recurrence-events'], ['no-recurrence-events'], ['recurrence-events'], ['no-recurrence-events'],
['recurrence-events'], ['no-recurrence-events'], ['recurrence-events'], ['no-recurrence-events']]



In [4]:
#INPUT [uncomment & modify if required]
labelencoder = LabelEncoder()
ordinalencoder = OrdinalEncoder()

In [5]:
X_train = np.array(X_train)

In [6]:
X_train = X_train.astype(str)

In [7]:
X_train

array([['40-49', 'premeno', '10-14', ..., 'right', 'right_low', 'no'],
       ['50-59', 'ge40', '10-14', ..., 'right', 'left_up', 'no'],
       ['40-49', 'ge40', '20-24', ..., 'left', 'left_low', 'no'],
       ...,
       ['60-69', 'ge40', '10-14', ..., 'right', 'left_low', 'no'],
       ['60-69', 'ge40', '40-44', ..., 'right', 'left_low', 'no'],
       ['60-69', 'ge40', '45-49', ..., 'left', 'central', 'no']],
      dtype='<U9')

In [8]:
X_train[0]

array(['40-49', 'premeno', '10-14', '0-2', 'no', '1', 'right',
       'right_low', 'no'], dtype='<U9')

In [9]:
y_train=np.array(y_train).reshape((len(y_train),1))



In [10]:
y_train = y_train.astype(str)

In [11]:
y_train

array([['no-recurrence-events'],
       ['no-recurrence-events'],
       ['no-recurrence-events'],
       ['recurrence-events'],
       ['no-recurrence-events'],
       ['no-recurrence-events'],
       ['recurrence-events'],
       ['recurrence-events'],
       ['no-recurrence-events'],
       ['recurrence-events'],
       ['no-recurrence-events'],
       ['no-recurrence-events'],
       ['recurrence-events'],
       ['no-recurrence-events'],
       ['recurrence-events'],
       ['no-recurrence-events'],
       ['recurrence-events'],
       ['no-recurrence-events'],
       ['recurrence-events'],
       ['no-recurrence-events'],
       ['no-recurrence-events'],
       ['recurrence-events'],
       ['no-recurrence-events'],
       ['recurrence-events'],
       ['no-recurrence-events'],
       ['recurrence-events'],
       ['no-recurrence-events'],
       ['recurrence-events'],
       ['no-recurrence-events'],
       ['no-recurrence-events'],
       ['no-recurrence-events'],
       ['no-r

In [12]:
#y_train.astype(str)
#AttributeError                            Traceback (most recent call last)
#Input In [17], in <cell line: 1>()
#----> 1 y_train.astype(str)

#AttributeError: 'list' object has no attribute 'astype'




y_train=np.array(y_train).reshape((len(y_train),1))
y_train.astype(str)

X_train.reshape(-1,1)
y_train.reshape(-1,1)

i_X=[1,2,3]
i_y = [1,2,3]

#for i_X in X_train.astype(str) and i_y in y_train.astype(str):
result_X = ordinalencoder.fit_transform(X_train.astype(str))
result_y = labelencoder.fit_transform(y_train.astype(str))
#write your Logic here:  


#OUTPUT [uncomment & modify if required]  
print(result_X)
print(result_y)

Answer for above program

[[2. 2. 1. ... 1. 4. 0.]
 [3. 0. 1. ... 1. 2. 0.]
 [2. 0. 3. ... 0. 1. 0.]
 ...
 [4. 0. 1. ... 1. 1. 0.]
 [4. 0. 7. ... 1. 1. 0.]
 [4. 0. 8. ... 0. 0. 0.]]
[0 0 0 1 0 0 1 1 0 1 0 0 1 0 1 0 1 0 1 0 0 1 0 1 0 1 0 1 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 1 1 0 0 1 0 1 0 0 0 0 0 1 1 1 0 1 0 0
 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 1 0 0 0
 0 0 0 0 1 1 0 1 0 1 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 1 0 0 0 1 1 1
 1 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 1 0 1 0 0
 0 0 0 1 0 1 1 0 0

In [13]:
#for i_X in X_train.astype(str) and i_y in y_train.astype(str):
result_X = ordinalencoder.fit_transform(X_train)
result_y = labelencoder.fit_transform(y_train)


In [18]:
# I'm getting results in this way
print(result_X) 

[[2. 2. 1. ... 1. 4. 0.]
 [3. 0. 1. ... 1. 2. 0.]
 [2. 0. 3. ... 0. 1. 0.]
 ...
 [4. 0. 1. ... 1. 1. 0.]
 [4. 0. 7. ... 1. 1. 0.]
 [4. 0. 8. ... 0. 0. 0.]]


In [19]:
print(result_y)

[0 0 0 1 0 0 1 1 0 1 0 0 1 0 1 0 1 0 1 0 0 1 0 1 0 1 0 1 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 1 1 0 0 1 0 1 0 0 0 0 0 1 1 1 0 1 0 0
 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 1 0 0 0
 0 0 0 0 1 1 0 1 0 1 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 1 0 0 0 1 1 1
 1 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 1 0 1 0 0
 0 0 0 1 0 1 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 0 0 1 1 0 0 0
 1 0 1 0 1 0]


In [20]:
# results should be this way 
result_X[0]

array([2., 2., 1., 0., 1., 0., 1., 4., 0.])

In [22]:
result_y[0]

0

In [24]:
#OUTPUT [uncomment & modify if required]  

print(result_X)

print(result_y)

[[2. 2. 1. ... 1. 4. 0.]
 [3. 0. 1. ... 1. 2. 0.]
 [2. 0. 3. ... 0. 1. 0.]
 ...
 [4. 0. 1. ... 1. 1. 0.]
 [4. 0. 7. ... 1. 1. 0.]
 [4. 0. 8. ... 0. 0. 0.]]
[0 0 0 1 0 0 1 1 0 1 0 0 1 0 1 0 1 0 1 0 0 1 0 1 0 1 0 1 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 1 1 0 0 1 0 1 0 0 0 0 0 1 1 1 0 1 0 0
 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 1 0 0 0
 0 0 0 0 1 1 0 1 0 1 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 1 0 0 0 1 1 1
 1 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 1 0 1 0 0
 0 0 0 1 0 1 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 0 0 1 1 0 0 0
 1 0 1 0 1 0]
